package cli;

public enum Mode {
    INSERT_CAKE,
    INSERT_HERSTELLER,
    DISPLAY_HERSTELLER,
    DISPLAY_CAKE,
    DISPLAY_ALLERGEN,
    DISPLAY_KEINE_ALLERGEN,
    DELETE_CAKE,
    UPDATE_INSPECTDATE
}
